### ISSUE TITLE
[FEATURE] Get signature level offset dynamically

### ISSUE THREAD

**Issue by riesha** [Idov31/Nidhogg#36]
More of a QoL change than anything but instead of hardcoding offsets and choosing them from the windows version you can get it dynamically by getting the base addr of `PsGetProcessSignatureLevel` and looking at these bytes 
![ida64_7SOYoSGz6J](https://github.com/Idov31/Nidhogg/assets/58556779/6f1854f8-9429-4636-9dac-21cb27bc7a99)

**Comment by Flerov** [comment]
How about a pdb parser?
If you dont have one you can use mine.
Would go along the line of
````
...
	// Symbol offset
	DWORD64 symbolOffsetPlaceholder;
	LPCSTR str = "_EPROCESS";
	symbolOffsetPlaceholder = GetSymbolOffset(sym_ctx, str);
	printf("Symbol at: 0x%llx\n", symbolOffsetPlaceholder);

	// Field Offset from a Symbol
	DWORD64 fieldOffsetPlaceholder;
	LPCWSTR str2 = L"ActiveProcessLinks";
	fieldOffsetPlaceholder = GetFieldOffset(sym_ctx, str, str2);
	printf("Symbol at: 0x%llx\n", fieldOffsetPlaceholder);
```

**Comment by Idov31** [comment]
@Flerov  PDB parser isn't a suitable idea for this case since you would need to:
A. Know the windows version of the target machine and in that case you wouldn't need to fetch it dynamically.
B. Download the PDB to the target's machine, parse it and delete it in the end - a thing that will take both space and more time than binary searching or constant offset.

However, I appreciate your suggestion and if you have other suggestions feel free to submit a PR / create another feature request :)
