### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by scareing** [Idov31/Nidhogg#5]
> 我想我已修复它，如果您仍然遇到 BSOD，请重新打开此问题 :)。

WIN10  Microsoft Windows [version 10.0.18363.418]

When I use PChunter to detect its stealth effect，The system immediately blue screen

![image](https://user-images.githubusercontent.com/42691451/172437616-b9e8b803-416c-42c0-9085-5aa8f270f03c.png)

_Originally posted by @scareing in https://github.com/Idov31/Nidhogg/issues/3#issuecomment-1148919201_

**Comment by Idov31** [comment]
Hi,
Thank you for opening the issue, did you run any certain function or when you just ran PChunter it gave BSOD?
And can you please send me the link from where you downloaded PChunter so I can recreate it?

**Comment by C4n3xp** [comment]
RemoveProcessLinks can not bypass PatchGuard

**Comment by Idov31** [comment]
As @C4n3xp said, Nidhogg is not (at least not yet) designed to bypass PatchGuard. 
Since Nidhogg is an unsigned driver, PatchGuard won't allow it to register the process and file routines and can cause KERNEL_SECURITY_CHECK_FAILURE on call. 
To test and load the driver without getting BSOD from PatchGuard you need to either follow the instructions I mentioned to setup & test the driver or sign the driver or use a known PatchGuard bypass.

**Comment by scareing** [comment]
No, no, no, I used the leaked NVIDIA signature
The case of BSOD still exists

**Comment by Idov31** [comment]
I don't know if it is still a valid signature, assuming it is, which functionality caused the BSOD?
